"""Portfolio loading, ranking, and reporting modules."""

from pe_scanner.portfolios.loader import (
    LoaderConfig,
    Portfolio,
    PortfolioType,
    Position,
    get_config as get_loader_config,
    load_all_portfolios,
    load_portfolio,
    merge_portfolios,
    validate_portfolio,
)
from pe_scanner.portfolios.ranker import (
    Confidence,
    RankedPosition,
    RankingConfig,
    RankingResult,
    Signal,
    SIGNAL_INFO,
    assign_signal,
    calculate_action_priority,
    calculate_confidence,
    categorize_by_action,
    get_actionable_summary,
    get_config as get_ranking_config,
    get_top_opportunities,
    rank_portfolio,
    rank_positions,
)
from pe_scanner.portfolios.reporter import (
    Report,
    ReportConfig,
    ReportFormat,
    format_position_detail,
    format_position_row,
    generate_buy_section,
    generate_hold_section,
    generate_methodology_section,
    generate_report,
    generate_sell_section,
    generate_summary,
    generate_text_report,
    generate_warnings_section,
    print_to_console,
    save_report,
)

__all__ = [
    # Loader
    "Portfolio",
    "PortfolioType",
    "Position",
    "load_all_portfolios",
    "load_portfolio",
    "merge_portfolios",
    "validate_portfolio",
    # Ranker
    "Confidence",
    "RankedPosition",
    "RankingConfig",
    "RankingResult",
    "Signal",
    "SIGNAL_INFO",
    "assign_signal",
    "calculate_action_priority",
    "calculate_confidence",
    "categorize_by_action",
    "get_actionable_summary",
    "get_ranking_config",
    "get_top_opportunities",
    "rank_portfolio",
    "rank_positions",
    # Reporter
    "Report",
    "ReportConfig",
    "ReportFormat",
    "format_position_detail",
    "format_position_row",
    "generate_buy_section",
    "generate_hold_section",
    "generate_methodology_section",
    "generate_report",
    "generate_sell_section",
    "generate_summary",
    "generate_text_report",
    "generate_warnings_section",
    "print_to_console",
    "save_report",
]
